# Copyright 2026 Ronny Trommer <ronny@no42.org>
# SPDX-License-Identifier: MIT
# Generated by Django 6.0.6 on 2026-06-30 07:37

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dcim', '0237_module_remove_local_context_data'),
        ('extras', '0139_alter_customfieldchoiceset_extra_choices'),
        ('ipam', '0092_iprange_host_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('assigned_object_id', models.PositiveBigIntegerField()),
                ('exclude', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('additional_ips', models.ManyToManyField(blank=True, related_name='+', to='ipam.ipaddress')),
                ('assigned_object_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(models.Q(('app_label', 'dcim'), ('model', 'device')), models.Q(('app_label', 'virtualization'), ('model', 'virtualmachine')), _connector='OR')), on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
                ('management_ip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ipam.ipaddress')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'monitoring override',
                'verbose_name_plural': 'monitoring overrides',
                'ordering': ('pk',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MonitoredService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ipam.ipaddress')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('override', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='netbox_opennms.monitoringoverride')),
            ],
            options={
                'verbose_name': 'monitored service',
                'verbose_name_plural': 'monitored services',
                'ordering': ('override', 'ip_address', 'name'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MonitoringProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('scan_interval', models.CharField(default='1d', max_length=32)),
                ('default_interfaces', models.CharField(default='primary', max_length=16)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'monitoring profile',
                'verbose_name_plural': 'monitoring profiles',
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MonitoringPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('rule_class', models.CharField(blank=True, max_length=255)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('preset', models.CharField(blank=True, max_length=50)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='netbox_opennms.monitoringprofile')),
            ],
            options={
                'verbose_name': 'monitoring policy',
                'verbose_name_plural': 'monitoring policies',
                'ordering': ('profile', 'name'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MonitoringDetector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('rule_class', models.CharField(blank=True, max_length=255)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('preset', models.CharField(blank=True, max_length=50)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detectors', to='netbox_opennms.monitoringprofile')),
            ],
            options={
                'verbose_name': 'monitoring detector',
                'verbose_name_plural': 'monitoring detectors',
                'ordering': ('profile', 'name'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MonitoringAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dcim.devicerole')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='netbox_opennms.monitoringprofile')),
            ],
            options={
                'verbose_name': 'monitoring assignment',
                'verbose_name_plural': 'monitoring assignments',
                'ordering': ('site', 'role'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='monitoringoverride',
            constraint=models.UniqueConstraint(fields=('assigned_object_type', 'assigned_object_id'), name='netbox_opennms_monitoringoverride_unique_object'),
        ),
        migrations.AddConstraint(
            model_name='monitoredservice',
            constraint=models.UniqueConstraint(fields=('override', 'ip_address', 'name'), name='netbox_opennms_monitoredservice_unique_service'),
        ),
        migrations.AddConstraint(
            model_name='monitoringpolicy',
            constraint=models.UniqueConstraint(fields=('profile', 'name'), name='netbox_opennms_monitoringpolicy_unique_name'),
        ),
        migrations.AddConstraint(
            model_name='monitoringdetector',
            constraint=models.UniqueConstraint(fields=('profile', 'name'), name='netbox_opennms_monitoringdetector_unique_name'),
        ),
        migrations.AddConstraint(
            model_name='monitoringassignment',
            constraint=models.UniqueConstraint(fields=('site', 'role'), name='netbox_opennms_monitoringassignment_unique_scope', nulls_distinct=False),
        ),
    ]
