# Generated by Django 6.0.6 on 2026-06-26 08:51
# Copyright 2026 Ronny Trommer <ronny@no42.org>
# SPDX-License-Identifier: MIT

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0092_iprange_host_indexes'),
        ('netbox_opennms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringprofile',
            name='management_ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ipam.ipaddress'),
        ),
    ]
