# Generated by Django 6.0.6 on 2026-06-27 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0092_iprange_host_indexes'),
        ('netbox_opennms', '0002_monitoringprofile_management_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringprofile',
            name='additional_ips',
            field=models.ManyToManyField(blank=True, related_name='+', to='ipam.ipaddress'),
        ),
    ]
