# Generated by Django 6.0.6 on 2026-06-27 07:11
# Copyright 2026 Ronny Trommer <ronny@no42.org>
# SPDX-License-Identifier: MIT

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0139_alter_customfieldchoiceset_extra_choices'),
        ('ipam', '0092_iprange_host_indexes'),
        ('netbox_opennms', '0003_monitoringprofile_additional_ips'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ipam.ipaddress')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='netbox_opennms.monitoringprofile')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'monitored service',
                'verbose_name_plural': 'monitored services',
                'ordering': ('profile', 'ip_address', 'name'),
                'constraints': [models.UniqueConstraint(fields=('profile', 'ip_address', 'name'), name='netbox_opennms_monitoredservice_unique_service')],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
