# Generated by Django 6.0.6 on 2026-06-27 09:08
# Copyright 2026 Ronny Trommer <ronny@no42.org>
# SPDX-License-Identifier: MIT

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_opennms', '0004_monitoredservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringprofile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
