# Generated by Django 6.0.6 on 2026-06-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_opennms', '0005_monitoringprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringprofile',
            name='last_synced_foreign_source',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
