# Copyright 2026 Ronny Trommer <ronny@no42.org>
# SPDX-License-Identifier: MIT
# Generated by Django 6.0.6 on 2026-07-03 15:51

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0140_imageattachment_image_size'),
        ('netbox_opennms', '0005_remove_monitoringoverride_additional_ips_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('netbox_source', models.CharField(max_length=100)),
                ('asset_field', models.CharField(max_length=64)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_mappings', to='netbox_opennms.requisition')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'asset mapping',
                'verbose_name_plural': 'asset mappings',
                'ordering': ('requisition', 'asset_field'),
                'constraints': [models.UniqueConstraint(fields=('requisition', 'asset_field'), name='netbox_opennms_assetmapping_unique_field')],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MetadataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('scope', models.CharField(default='node', max_length=16)),
                ('context', models.CharField(default='requisition', max_length=64)),
                ('key', models.CharField(max_length=100)),
                ('value_source', models.CharField(blank=True, max_length=100)),
                ('literal_value', models.CharField(blank=True, max_length=255)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_entries', to='netbox_opennms.requisition')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'metadata entry',
                'verbose_name_plural': 'metadata entries',
                'ordering': ('requisition', 'scope', 'context', 'key'),
                'constraints': [models.UniqueConstraint(fields=('requisition', 'scope', 'context', 'key'), name='netbox_opennms_metadataentry_unique_meta')],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
